---
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install EPEL Repository
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install backupninja dependencies
  package:
    name: "{{ backupninja_dependecies }}"
    state: present

- name: Ensure backupninja backup dir already exists
  file:
    path: "{{ backupninja_main_backupdir }}"
    owner: root
    group: root
    state: directory

- import_tasks: configure.yml
